cloud_passthrough_filter_node:
  ros__parameters:
    use_sim_time: true

    input_topic: "/vanjee/lidar"
    output_topic: "/vanjee/lidar_passthrough"

    filter_order: "xyz"
    enable_x: true
    enable_y: true
    enable_z: true

    # 默认按 front_ground_segmentation 的直通区间，现场再改
    limit_min_x: 0.0
    limit_max_x: 3.5
    limit_min_y: -2.0
    limit_max_y: 2.0
    limit_min_z: -0.2
    limit_max_z: 0.4

    debug_mode: true
    debug_topic_x: "/vanjee/passthrough_x"
    debug_topic_y: "/vanjee/passthrough_y"
    debug_topic_z: "/vanjee/passthrough_z"

    memory_pool_size: 10
    memory_pool_reserve: 1000000
    cloud_log_interval_sec: 1.0

    # 我们自己的立方体，雷达中心，长宽高
    cube_length: 4.0
    cube_width: 4.0
    cube_height: 2.0

    # 细格 base；合成后横向=1×线间距，纵向=2×线间距
    removed_topic: "/vanjee/lidar_removed"
    enable_voxel_filter: true
    ang_h: 0.0034906585
    ang_v: 0.0174532925
    r_max: 8.0
    base_xy: 0.01
    base_z: 0.01
    max_xy: 0.5
    max_z: 0.5
    thr_ratio: 0.5
